name = "dbvisit-automation"
main = "src/main.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[browser]
binding = "MY_BROWSER"
